insert into cities (city_id, country_id, name) values (1, 6, 'Tokoname');
insert into cities (city_id, country_id, name) values (2, 1, 'Mernek');
insert into cities (city_id, country_id, name) values (3, 10, 'Liudong');
insert into cities (city_id, country_id, name) values (4, 4, 'Dzhalka');
insert into cities (city_id, country_id, name) values (5, 3, 'Lélouma');
insert into cities (city_id, country_id, name) values (6, 1, 'Bāglung');
insert into cities (city_id, country_id, name) values (7, 8, 'Czerwin');
insert into cities (city_id, country_id, name) values (8, 4, 'Limulan');
insert into cities (city_id, country_id, name) values (9, 1, 'Itaperuna');
insert into cities (city_id, country_id, name) values (10, 1, 'Otaslavice');
insert into cities (city_id, country_id, name) values (11, 10, 'Meliau');
insert into cities (city_id, country_id, name) values (12, 2, 'Del Valle');
insert into cities (city_id, country_id, name) values (13, 1, 'San Carlos');
insert into cities (city_id, country_id, name) values (14, 7, 'Jinping');
insert into cities (city_id, country_id, name) values (15, 8, 'Veiros');
insert into cities (city_id, country_id, name) values (16, 3, 'Surkh Bilandī');
insert into cities (city_id, country_id, name) values (17, 2, 'Padina');
insert into cities (city_id, country_id, name) values (18, 5, 'Léo');
insert into cities (city_id, country_id, name) values (19, 4, 'Hushan');
insert into cities (city_id, country_id, name) values (20, 3, 'Marmárion');
insert into cities (city_id, country_id, name) values (21, 1, 'Mahdishahr');
insert into cities (city_id, country_id, name) values (22, 1, 'Blois');
insert into cities (city_id, country_id, name) values (23, 7, 'Tangchi');
insert into cities (city_id, country_id, name) values (24, 10, 'Shifan');
insert into cities (city_id, country_id, name) values (25, 5, 'Bultfontein');
insert into cities (city_id, country_id, name) values (26, 10, 'Fraile Pintado');
insert into cities (city_id, country_id, name) values (27, 3, 'Aripuanã');
insert into cities (city_id, country_id, name) values (28, 8, 'Baitao');
insert into cities (city_id, country_id, name) values (29, 5, 'Tomakivka');
insert into cities (city_id, country_id, name) values (30, 9, 'Poddor’ye');
insert into cities (city_id, country_id, name) values (31, 7, 'Amiens');
insert into cities (city_id, country_id, name) values (32, 7, 'Qufu');
insert into cities (city_id, country_id, name) values (33, 1, 'Puerto Berrío');
insert into cities (city_id, country_id, name) values (34, 9, 'Panórama');
insert into cities (city_id, country_id, name) values (35, 10, 'Yŏnan-ŭp');
insert into cities (city_id, country_id, name) values (36, 9, 'Pieksämäki');
insert into cities (city_id, country_id, name) values (37, 7, 'Niihama');
insert into cities (city_id, country_id, name) values (38, 4, 'Chabany');
insert into cities (city_id, country_id, name) values (39, 2, 'Galimuyod');
insert into cities (city_id, country_id, name) values (40, 1, 'Alvaro Obregon');
insert into cities (city_id, country_id, name) values (41, 5, 'Kebon');
insert into cities (city_id, country_id, name) values (42, 1, 'Kuncen');
insert into cities (city_id, country_id, name) values (43, 7, 'Diez de Octubre');
insert into cities (city_id, country_id, name) values (44, 9, 'Ouro Preto do Oeste');
insert into cities (city_id, country_id, name) values (45, 7, 'Lisiy Nos');
insert into cities (city_id, country_id, name) values (46, 5, 'Narol');
insert into cities (city_id, country_id, name) values (47, 3, 'Sim');
insert into cities (city_id, country_id, name) values (48, 9, 'Mounlapamôk');
insert into cities (city_id, country_id, name) values (49, 1, 'Erada');
insert into cities (city_id, country_id, name) values (50, 7, 'Ngembo');
insert into cities (city_id, country_id, name) values (51, 5, 'Saint-Ambroise');
insert into cities (city_id, country_id, name) values (52, 2, 'Alvide');
insert into cities (city_id, country_id, name) values (53, 7, 'Berendeyevo');
insert into cities (city_id, country_id, name) values (54, 1, 'Järfälla');
insert into cities (city_id, country_id, name) values (55, 8, 'Panite');
insert into cities (city_id, country_id, name) values (56, 10, 'Yuezhao');
insert into cities (city_id, country_id, name) values (57, 3, 'Cícero Dantas');
insert into cities (city_id, country_id, name) values (58, 5, 'Krajan Puru');
insert into cities (city_id, country_id, name) values (59, 1, 'Acobambilla');
insert into cities (city_id, country_id, name) values (60, 2, 'Pardesiyya');
insert into cities (city_id, country_id, name) values (61, 2, 'Město Libavá');
insert into cities (city_id, country_id, name) values (62, 3, 'Cherryville');
insert into cities (city_id, country_id, name) values (63, 5, 'Sozopol');
insert into cities (city_id, country_id, name) values (64, 8, 'Ebu');
insert into cities (city_id, country_id, name) values (65, 3, 'Várzea de Sintra');
insert into cities (city_id, country_id, name) values (66, 4, 'Angasmarca');
insert into cities (city_id, country_id, name) values (67, 2, 'Johor Bahru');
insert into cities (city_id, country_id, name) values (68, 5, 'Jianxin');
insert into cities (city_id, country_id, name) values (69, 4, 'Astypálaia');
insert into cities (city_id, country_id, name) values (70, 10, 'Chemerivtsi');
insert into cities (city_id, country_id, name) values (71, 1, 'Daohe');
insert into cities (city_id, country_id, name) values (72, 10, 'Linëvo');
insert into cities (city_id, country_id, name) values (73, 1, 'Smidary');
insert into cities (city_id, country_id, name) values (74, 8, 'Obo');
insert into cities (city_id, country_id, name) values (75, 4, 'Vilya');
insert into cities (city_id, country_id, name) values (76, 3, 'Wiśniewo');
insert into cities (city_id, country_id, name) values (77, 2, 'Taibao');
insert into cities (city_id, country_id, name) values (78, 9, 'Moshkovo');
insert into cities (city_id, country_id, name) values (79, 4, 'Chlumec nad Cidlinou');
insert into cities (city_id, country_id, name) values (80, 1, 'Lopez Jaena');
insert into cities (city_id, country_id, name) values (81, 5, 'San Rafael');
insert into cities (city_id, country_id, name) values (82, 9, 'Kallinge');
insert into cities (city_id, country_id, name) values (83, 10, 'La’ershan');
insert into cities (city_id, country_id, name) values (84, 1, 'Cabreúva');
insert into cities (city_id, country_id, name) values (85, 8, 'Windsor');
insert into cities (city_id, country_id, name) values (86, 5, 'Xinlin');
insert into cities (city_id, country_id, name) values (87, 9, 'Mangge');
insert into cities (city_id, country_id, name) values (88, 4, 'Galatás');
insert into cities (city_id, country_id, name) values (89, 8, 'Bojano');
insert into cities (city_id, country_id, name) values (90, 6, 'Granada');
insert into cities (city_id, country_id, name) values (91, 4, 'Hedong');
insert into cities (city_id, country_id, name) values (92, 10, 'Yulin');
insert into cities (city_id, country_id, name) values (93, 8, 'Xiyang');
insert into cities (city_id, country_id, name) values (94, 1, 'Imbang');
insert into cities (city_id, country_id, name) values (95, 6, 'Áno Kalentíni');
insert into cities (city_id, country_id, name) values (96, 7, 'Pau');
insert into cities (city_id, country_id, name) values (97, 8, 'Guisijan');
insert into cities (city_id, country_id, name) values (98, 8, 'Machakos');
insert into cities (city_id, country_id, name) values (99, 1, 'Lebedinovka');
insert into cities (city_id, country_id, name) values (100, 1, 'Tianyu');
